import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Preuve AI — Should you build this idea?",
  description:
    "Validate your startup idea before you build. Get a viability score, competitor map, market sizing, and blind spots — generated by Claude.",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="min-h-screen bg-ink font-sans antialiased">
        {children}
      </body>
    </html>
  );
}
